# Generated by Django 4.0.6 on 2022-08-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBankCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_Detail', models.TextField(max_length=99999)),
                ('Question_Image', models.TextField(default=None, max_length=99999, null=True)),
                ('ID_Subject', models.IntegerField()),
                ('Question_AnswerA', models.TextField(max_length=99999)),
                ('Question_AnswerB', models.TextField(max_length=99999)),
                ('Question_AnswerC', models.TextField(max_length=99999)),
                ('Question_AnswerD', models.TextField(max_length=99999)),
                ('Correct_Answer', models.TextField(max_length=99999)),
                ('stt', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'question_bank_csv',
            },
        ),
    ]
